<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.0 .\device1.glb
-->

<script>
	import { T, forwardEventHandlers } from '@threlte/core';
	import { Group } from 'three';
	import { useGltf } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('3dmodel/device1.glb');
	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.geometry_0.geometry} material={gltf.nodes.geometry_0.material} />
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
